"""
Sandbox Tests - Feel free to modify!

The test class below can be considered as a playground - feel free to modify it as you need, e.g.:
- add your own custom tests
- delete existing tests
- modify test contents or expected output

The results of tests from this file will always be at the beginning of the report generated by clicking
the "Run" button.

The results of these tests do not affect the final score (unless the project fails to build).
"""
import sys
import os
import unittest
from functools import wraps
import signal

# Add current directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from integer_container_impl import IntegerContainerImpl


class TimeoutError(Exception):
    pass


def timeout(seconds):
    """Decorator to add timeout to test methods."""
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            def handler(signum, frame):
                raise TimeoutError(f"Test timed out after {seconds} seconds")
            
            old_handler = signal.signal(signal.SIGALRM, handler)
            signal.setitimer(signal.ITIMER_REAL, seconds)
            
            try:
                result = func(*args, **kwargs)
            finally:
                signal.setitimer(signal.ITIMER_REAL, 0)
                signal.signal(signal.SIGALRM, old_handler)
            
            return result
        return wrapper
    return decorator


failureException = Exception


class SandboxTests(unittest.TestCase):
    """
    The test class below can be considered as a playground - feel free to modify it as you need, e.g.:
    - add your own custom tests
    - delete existing tests
    - modify test contents or expected output

    The results of tests from this file will always be at the beginning of the report generated by clicking
    the "Run" button.

    The results of these tests do not affect the final score (unless the project fails to build).
    """
    
    @classmethod
    def setUpClass(cls):
        cls.container = IntegerContainerImpl()
    
    @timeout(0.4)
    def test_sample(self):
        self.assertEqual(self.container.add(5), 1)
        self.assertEqual(self.container.add(10), 2)
        # Add more assertions here to test your implementation


if __name__ == '__main__':
    unittest.main()
